#spring.datasource.url=jdbc:mysql://localhost:3306/douban
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douban
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#debug: true
